python:3.5.1-alpine doesn’t run with vboxsf.
```
$ docker logs alpine
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 232-652-776
192.168.33.1 - - [23/Mar/2016 17:37:52] "GET / HTTP/1.1" 200 -
 * Detected change in '/app/app.py', reloading
 * Restarting with stat
  File "app.py", line 13

                                      ^
SyntaxError: unexpected EOF while parsing
```